version: 2.1
orbs:
  node: circleci/node@2.0.3

terraform: &terraform
  working_directory: ~/pizza-aplication/terraform
  docker:
    - image: hashicorp/terraform:0.12.24
  environment:
    TF_IN_AUTOMATION: true
    TF_VAR_AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    TF_VAR_AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    TF_VAR_AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

jobs:
  build:
    executor: node/default
    working_directory: ~/pizza-aplication
    environment:
        BACKEND_API_ENV: $BACKEND_API
        CI: true
    steps:
        - checkout
        - run:
            name: Set env file
            command: |
                echo "REACT_APP_API_URL=$BACKEND_API_ENV" >> .env
        - run:
            name: Install
            command: npm install
        - run:
            name: Unit test
            command: echo Success
        - run:
            name: Build
            command: CI=false npm run build
        - persist_to_workspace:
            root: ~/pizza-aplication
            paths: .
  init:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/pizza-aplication
      - run:
          name: init
          command: |
            ls -la
            pwd
            terraform init
      - persist_to_workspace:
          root: ~/pizza-aplication
          paths: . 

  plan:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/pizza-aplication
      - run:
          name: plan
          command: terraform plan
      - store_artifacts:
          path: ~/pizza-aplication/terraform/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: ~/pizza-aplication
          paths: .

  apply:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/pizza-aplication
      - run:
          name: apply
          command: terraform apply -auto-approve
      - run:
          name: show
          command: terraform show -no-color > tfresult
      - store_artifacts:
          path: ~/pizza-aplication/terraform/tfresult
          destination: tfresult

  deploy:
    

  destroy:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/pizza-aplication
      - run:
          name: destroy app
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build_front:
    jobs:
      - build
      - init:
         requires:
            - build
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
      - destroy:
          requires:
            - plan
          filters:
            branches:
              only:
                - destroy
